# Generated by Django 3.2.1 on 2021-05-12 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Roll_Number', models.IntegerField(primary_key=True, serialize=False)),
                ('Dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Addmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('grade1', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('F', 'F')], max_length=50)),
                ('rollnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
